### ISSUE TITLE
PMMO Sending Recipes on login causes Timed Out from lag

### ISSUE THREAD

**Issue by LunafeyLazuli** [Caltinor/Project-MMO-2.0#78]
**Describe the bug**
When ever a player joins the server for the first time, most of the time it locks up the server to the point where it times everyone out expect for the person who just joined.

**Expected behavior**
To not time everyone out

**To Reproduce**
1. Start up a server that has a good amount of mods
2. Start a spark profile
3. Get people to join for the first time on a fresh world
4. Server locks up
5. Everyone times out
6. After a minute everyone can rejoin again
7. Happens all over again next time someone else joins for the first time

**Screenshots**
https://spark.lucko.me/iGLs565YFr
https://gyazo.com/85e88d76ffc43caa8f09883507efbacf

**Versions:**
 - Minecraft: 1.16.5
 - Loader: Forge-36.2.39
 - PMMO: Project_MMO-1.16.5-3.67.6.jar

**Additional context**
Pretty much check the link for the spark profile, but we believe that it's PMMO sending recipes when a player logs in is what's doing it

**Comment by Caltinor** [comment]
With a large enough pack, this makes sense.  if you disable crafting reqs, that should solve the time out problem.

**Comment by LunafeyLazuli** [comment]
Sweet can do, cause I know that the crafting reqs don't really work on modded items half the time anyways, ty!

**Comment by LunafeyLazuli** [comment]
Can confirm, after turning it off and restarting the server, it still happens

**Comment by LunafeyLazuli** [comment]
So it's more than likely just an issue that PMMO is having with JEI, or vice versa, but it's def between the two mods and it's causing a TON of lag.

**Comment by TheTaterLord** [comment]
swapping from jei to rei can stop this interaction. this appears to be the tooltip caching error yet again just on a worse scale

**Comment by LunafeyLazuli** [comment]
That isn't an actual fix to the problem though

**Comment by Caltinor** [comment]
> So it's more than likely just an issue that PMMO is having with JEI, or vice versa, but it's def between the two mods and it's causing a TON of lag.

we talked about this before, but for the issue history, JEI is known to cache a lot of data on tooltips and the likes.  since PMMO adds tooltips for literally every item in the game, that adds considerable load to that system.  with enough mods that can cause the process of caching to surpass the

**Comment by LunafeyLazuli** [comment]
Yeah which is understandable, I'm just wanting to know if there's a possible fix for it, sorry xD

**Comment by Caltinor** [comment]
Basically, what Tater said.  Switch to REI.  JEI's caching problem isn't limited to PMMO.  any sufficiently large pack ends up with this problem.  unless JEI finds a way to optimize their caching, this is the case.  You can try having folks join a single player world first, to see if that helps.

**Comment by LunafeyLazuli** [comment]
The thing is that we've run a 300 mod pack with JEI and never had issues like this until we installed PMMO, which is why I'm posting it here to see if there's some possible fix for it, or if the solution is just to switch

**Comment by Caltinor** [comment]
Think of pmmo as doubling your JEI load.  if you have 150 mods and PMMO makes that 300 load and JEI can handle 350 then you're good, but at 300 mods and 600 load it's too much.  PMMO definitely plays a role, but there's nothing we can do to change how JEI caches tooltips.  We are using forge's provided tooltip method, so JEI is 100% at fault here.

**Comment by LunafeyLazuli** [comment]
Sweet, then I will *attempt* to poke the JEI gods and see if there's any sort of fix they can do too XD I'm only trying to keep JEI so much is because we have some integrations with it with other mods that helps a lot with other stuff, it's just that loading time to the server is pretty painful haha
